//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by dptest.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDD_NEW_ENT                     130
#define IDD_GET_ENT_INF                 131
#define IDD_OPENCHANNDLG                132
#define IDD_SEND                        133
#define IDD_RECVDLG                     134
#define IDD_DESTROYPLAYER               136
#define IDD_OPENDLG                     137
#define IDC_FULLNAME                    1000
#define IDC_NICKNAME                    1001
#define IDC_PLAYERID                    1002
#define IDC_PLAYERID_FROM               1003
#define IDC_GETINFO                     1004
#define IDC_TARGET                      1005
#define IDC_SOURCE                      1006
#define IDC_CHANNELID                   1007
#define IDC_MESSAGE                     1008
#define IDC_LOCENT                      1009
#define IDC_PLAYERID_TO                 1010
#define IDC_EDIT2                       1013
#define IDC_DPRECEIVE_HIGHPRIORITY          1015
#define IDC_DPRECEIVE_NORMAL                1016
#define IDC_DPRECEIVE_PEEK                  1017
#define IDC_DPRECEIVE_TOPLAYER              1018
#define IDC_DPRECEIVE_TRYONCEFIRST          1019
#define IDC_DPSEND_BLOCKING                 1020
#define IDC_DPSEND_GUARANTEE                1021
#define IDC_DPSEND_HIGHPRIORITY             1022
#define IDC_DPSEND_REPLYREQUESTED           1023
#define IDC_DPSEND_TRYONCE                  1024
#define IDC_ALLPERMUTES                 1026
#define IDC_NUMSENDS                    1027
#define IDC_NUMPLAYERS                  1029
#define IDC_SHORTBUFF                   1030
#define ID_TEST_NEWENTITY               32771
#define ID_TEST_SEND                    32772
#define ID_TEST_INITIALISE              32773
#define ID_TEST_SHUTDOWN                32774
#define ID_TEST_GETNAMES                32775
#define ID_TEST_OPENCHANNEL             32776
#define ID_TEST_BEGINRECEIVE            32777
#define ID_TEST_ABORT                   32778
#define ID_TEST_CREATEOBJECT            32781
#define ID_TEST_DESTROYPLAYER           32782
#define ID_TEST_DIRECTPLAYENUMERATE     32783
#define ID_TEST_RELEASE                 32784
#define ID_GAMEID_DEFAULTGUID           32785
#define ID_GAMEID_ALTERNATEGUID         32786

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        138
#define _APS_NEXT_COMMAND_VALUE         32787
#define _APS_NEXT_CONTROL_VALUE         1031
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif

