/*===========================================================================*\
|
|  File:        cgchrint.h
|
|  Description: 
|       
|-----------------------------------------------------------------------------
|
|  Copyright (C) 1995 Microsoft Corporation.  All Rights Reserved.
|
|  Written by Moss Bay Engineering, Inc. under contract to Microsoft Corporation
|
\*===========================================================================*/
void    LoadCharInfo( CGameInfo * info );
CGameCharInfo *FindCharInfo( char *name );
void    LoadMyDLL( char *path, char *name );
