//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by IKLOWNS.RC
//
#define IDS_INFO_TITLE                  1
#define IDS_ERROR_TITLE                 2
#define IDS_INVALID_FILE                3
#define IDS_GDI_ERROR                   4
#define IDS_STARTUP_ERROR               5
#define IDR_GENERIC                     101
#define IDI_APP                         102
#define IDD_ABOUTBOX                    103
#define IDR_ACCELERATOR1                106
#define IDD_REMCONNABORTDLG             106
#define IDC_FILEDESCRIPTION             1000
#define IDC_PRODUCTVERSION              1001
#define IDC_LEGALCOPYRIGHT              1002
#define IDC_COMPANYNAME                 1003
#define IDC_LEGALTRADEMARKS             1004
#define OPTION_PLAY_START               2001
#define IDS_SOLO_PLAY                   2001
#define IDS_TWO_PLAYER                  2002
#define IDS_NET_PLAY                    2003
#define IDS_QUIT_GAME                   2004
#define OPTION_PLAY_END                 2004
#define IDS_INSTRUCTION_1               2005
#define IDS_INSTRUCTION_2               2006
#define CREDIT_START                    2100
#define IDS_LOAD_MSG                    2200
#define IDS_WIN_START                   2300
#define IDS_WIN_1                       2300
#define IDS_WIN_2                       2301
#define IDS_WIN_3                       2302
#define IDS_WIN_4                       2303
#define IDS_WIN_5                       2304
#define IDS_WIN_6                       2305
#define IDS_LOSE_START                  2400
#define IDS_LOSE_1                      2400
#define IDS_LOSE_2                      2401
#define IDS_LOSE_3                      2402
#define IDS_LOSE_4                      2403
#define IDS_LOSE_5                      2404
#define IDS_LOSE_6                      2405
#define IDM_NEW                         40001
#define IDM_OPEN                        40002
#define IDM_SAVE                        40003
#define IDM_SAVEAS                      40004
#define IDM_PRINT                       40005
#define IDM_PRINTSETUP                  40006
#define IDM_EXIT                        40007
#define IDM_UNDO                        40008
#define IDM_CUT                         40009
#define IDM_COPY                        40010
#define IDM_PASTE                       40011
#define IDM_LINK                        40012
#define IDM_LINKS                       40013
#define IDM_HELPCONTENTS                40014
#define IDM_HELPSEARCH                  40015
#define IDM_HELPHELP                    40016
#define IDM_ABOUT                       40017
#define IDA_LEFT                        40018
#define IDA_RIGHT                       40019
#define IDA_UP                          40020
#define IDA_DOWN                        40021
#define IDA_RETURN                      40022
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        107
#define _APS_NEXT_COMMAND_VALUE         40023
#define _APS_NEXT_CONTROL_VALUE         1005
#define _APS_NEXT_SYMED_VALUE           104
#endif
#endif
