/*===========================================================================*\
|
|  File:        cgtile.h
|
|  Description: 
|       
|-----------------------------------------------------------------------------
|
|  Copyright (C) 1995 Microsoft Corporation.  All Rights Reserved.
|
|  Written by Moss Bay Engineering, Inc. under contract to Microsoft Corporation
|
\*===========================================================================*/

#ifndef CGTILE_H
#define CGTILE_H

class CGTile
{
public:
    CGameTile();
    ~CGameTile();

private:
    CGameGraphic mGraphic;
};

