/*==========================================================================
 *
 *  Copyright (C) 1995 Microsoft Corporation. All Rights Reserved.
 *
 *  File:    stdafx.cpp
 *  Content: Precompiled Headers
 *              
 ***************************************************************************/


// stdafx.cpp : source file that includes just the standard includes
//  bee.pch will be the pre-compiled header
//  stdafx.obj will contain the pre-compiled type information

#define _AFX_NO_BSTR_SUPPORT
#include "stdafx.h"


